// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnkfzwcpvkafduzxwfdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRua2Z6d2NwdmthZmR1enh3ZmR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDkxODcsImV4cCI6MjA2NjI4NTE4N30.pvmjEOsvlPY-4NV4ShvAFEQu2TdeLr4e4GBk4irX6v8";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);